---
- name: Create a GCE VM instance through GCE Role
  hosts: localhost
  gather_facts: no
  vars:
    gce_instance_service_account: "{{ lookup('env', 'GCP_INSTANCE_SERVICE_ACCOUNT')}}"
  vars_files:
    - vars/gce_instance_custom_net.yml
  roles:
    - role: gce
